### ISSUE TITLE
False positive when a properties within an array item is modified

### ISSUE THREAD

**Issue by parodot** [smelukov/nano-equal#4]
**node**: 8.9.0
**npm**: 5.5.1

The scenario below produces a false positive.
```
const ne = require('nano-equal');
let oa = { 'a': 1, 'b': [1, { 'c': 'd' }], e: { 'a': [1, 2, '2'] } };
let ob = { 'a': 1, 'b': [1, { 'c': 'd' }], e: { 'a': [1, 2, '2'] } };

console.log(ne(oa, ob) ? 'equal' : 'not equal'); // equal
ob.b[1].d = 1
console.log(ne(oa, ob) ? 'equal' : 'not equal') // equal <- incorrect
```

Also the below scenario

```
console.log(ne(oa, ob) ? 'equal' : 'not equal'); // equal
ob.b.c = 1// this is valid js although b is an array
console.log(ne(oa, ob) ? 'equal' : 'not equal') // equal <- incorrect
```

[Testing deep equality](https://gist.github.com/parodot/6bd1beb76c855e0244feab7ba1b4fa66) gist has more tests

**Comment by smelukov** [comment]
Thanks for your report 👍

**Comment by smelukov** [comment]
I think that second case is not applicable for here cause arrays compares by its length and the elements (0, 1, 2, etc...), not like objects that compares by keys

**Comment by parodot** [comment]
Thanks for the quick response. 
I was just expecting feature parity with assert.deepEqual, hence the report. I would recommend that you consider that scenario as well or make a note of it in your readme. Since you are considering this library as an alternative to assert.deepEqual.
